<Workspace Version="0.9.1.3340" X="0" Y="0" zoom="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="60fa48e4-e37d-4067-ae46-b5fc5c6d61d8" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="82" y="92" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" CodeText="X = Autodesk.Point.ByCoordinates(21, 21, 21);&#xA;Y = [Imperative]&#xA;{&#xA;    return = X.X;&#xA;};" ShouldFocus="false" />
    <DSCoreNodesUI.Watch guid="39c65660-8575-43bc-8af7-f24225a6bd5b" type="DSCoreNodesUI.Watch" nickname="Watch" x="544.5" y="244.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="60fa48e4-e37d-4067-ae46-b5fc5c6d61d8" start_index="1" end="39c65660-8575-43bc-8af7-f24225a6bd5b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>