<Workspace Version="0.9.1.3262" X="0" Y="0" zoom="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="dd9f71f1-aa0c-4301-ac11-744c34a180c5" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="113" y="53" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" CodeText="p = Autodesk.Point.ByCoordinates(1, 1, 1);&#xA;v = Vector.ByCoordinates(4, 4, 4);&#xA;pt2 = Autodesk.Point.Add(p, v);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ad59f4ac-3fca-4e4f-b387-757ee74ea039" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.X" x="394.5" y="191.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.X" />
    <DSCoreNodesUI.Watch guid="dc61bae7-a661-477f-a438-ace939d958f4" type="DSCoreNodesUI.Watch" nickname="Watch" x="517.5" y="283.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="dd9f71f1-aa0c-4301-ac11-744c34a180c5" start_index="2" end="ad59f4ac-3fca-4e4f-b387-757ee74ea039" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ad59f4ac-3fca-4e4f-b387-757ee74ea039" start_index="0" end="dc61bae7-a661-477f-a438-ace939d958f4" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>